---

- name: install gitlab dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - openssh-server
    - openssl
    - policycoreutils-python
    - postfix
    - tzdata

- name: download repository config
  get_url:
    url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.repo?os={{ ansible_distribution | lower }}&dist={{ ansible_distribution_major_version }}"
    dest: /etc/yum.repos.d/gitlab_gitlab-ce.repo
  register: repo

- name: gitlab gpg keys present
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    - https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg
  when: repo is changed
  register: keys

- name: yum makecache
  command: yum makecache -y --disablerepo=* --enablerepo=gitlab*
  args:
    warn: no
  when: (repo is changed) or (keys is changed)

- name: install gitlab-ce
  yum:
    name: gitlab-ce
    state: present
    update_cache: yes
  notify: reconfigure gitlab
