---

- include: install.yml

- include: tls.yml

- name: template configuration file
  template:
    src: "{{ ansemjo_gitlab_template }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: reconfigure gitlab

- include: firewall.yml